config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	devise_for :users

	# resources :users do
	# 	resources :cardlists do
	# 		resources :cards
	# 		patch 'cards/:id/check' => 'cards#update2' , as: 'update2'
	# 	end
	# end

    get 'cardlists/:user_id/index' => 'cardlists#index' , as: 'cardlists_index'
    post 'cardlists/:user_id' => 'cardlists#create'
    get 'cardlists/index_all_users' => 'cardlists#index_all_users', as: 'cardlists_index_all_users'

	resources :users
	resources :cardlists do
		resource :favorites, only: [:create, :destroy]
		resources :cards
		patch 'cards/:id/check' => 'cards#update2' , as: 'update2'
	end

	root :to => 'root#top'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

        if user && user.admin?
              can :access, :rails_admin   # grant access to rails_admin
              can :manage, :all           # allow superadmins to do anything
            end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/views/cardlists/index.html.erb
<h1>マイカードリスト</h1>

<% if current_user == @user %>

	<%= form_for (@cardlist) do |c| %>
	<p>カードリスト名</p>
	<%= c.text_field :cardlist_name %>
	<%= c.submit '登録' %>
	<% end %>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>カードリスト名</th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @cardlists.each do |c| %>
			<tr>
				<td><%= c.cardlist_name %></td>
				<td>いいねの数</td>
				<td><%= link_to "学習", cardlist_path(c.id) %></td>
				<td><%= link_to "編集", edit_cardlist_path(c.id) %></td>
				<td><%= link_to "削除", cardlist_path(c.id), method: :delete, "data-confirm"=>"本当に削除しますか？" %></td>
			</tr>
			<%end%>
		</tbody>
	</table>

<% else %>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>カードリスト名</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @cardlists.each do |c| %>
			<tr>
				<td><%= c.cardlist_name %></td>
				<td><%= link_to "学習", cardlist_path(c.id) %></td>
			</tr>
			<%end%>
		</tbody>
	</table>

<% end %>